services:
  - type: web
    name: ai-pdf-extractor
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: AI_PROVIDER
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: AZURE_OPENAI_API_KEY
        sync: false
      - key: AZURE_OPENAI_ENDPOINT
        sync: false
      - key: AZURE_OPENAI_DEPLOYMENT
        sync: false
      - key: AZURE_OPENAI_API_VERSION
        value: 2024-02-15-preview
      - key: DEFAULT_MODEL
        value: gpt-4o

